<Project>

    <PropertyGroup>
        <RepoDirectory>$(MSBuildThisFileDirectory)</RepoDirectory>
        <RepoKind>GitHub</RepoKind> <!-- Valid values: AzureRepos | GitHub -->
    </PropertyGroup>

    <Import Project="eng\Versions.props"/>
    <Import Project="eng\Packaging.props"/>
    <Import Sdk="PostSharp.Engineering.Sdk" Project="BuildOptions.props"/>
    <Import Sdk="PostSharp.Engineering.Sdk" Project="StrongName.props"/>
    <Import Sdk="PostSharp.Engineering.Sdk" Project="SourceLink.props"/>

    <PropertyGroup>
        <NoWarn>SA0001</NoWarn>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        
        <!-- The latest version supported by Metalama Compiler may be higher that the latest version supported by Metalama Framework. -->
        <LangVersion>$(LangMaxVersion)</LangVersion>
    </PropertyGroup>

</Project>