package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildFeatures.CommitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ReleaseBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ReleaseBuild")) {
    check(paused == false) {
        "Unexpected paused: '$paused'"
    }
    paused = true

    features {
        val feature1 = find<CommitStatusPublisher> {
            commitStatusPublisher {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "%env.GITHUB_TOKEN%"
                    }
                }
            }
        }
        feature1.apply {
            publisher = github {
                githubUrl = "https://api.github.com"
                authType = personalToken {
                    token = "credentialsJSON:266d4d23-118e-4e28-b02f-c62f1dc9b1f1"
                }
            }
        }
        val feature2 = find<PullRequests> {
            pullRequests {
                vcsRootExtId = "${DslContext.settingsRoot.id}"
                provider = github {
                    authType = token {
                        token = "%env.GITHUB_TOKEN%"
                    }
                    filterTargetBranch = "+:refs/heads/develop/2025.2"
                    filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
                }
            }
        }
        feature2.apply {
            provider = github {
                serverUrl = ""
                authType = token {
                    token = "credentialsJSON:266d4d23-118e-4e28-b02f-c62f1dc9b1f1"
                }
                filterSourceBranch = ""
                filterTargetBranch = "+:refs/heads/develop/2025.2"
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }
}
