
<Project>

    <PropertyGroup>
        <MetalamaBackstageVersion>2024.2.24</MetalamaBackstageVersion>
        <MetalamaCompilerVersion>2024.2.18</MetalamaCompilerVersion>
        <MetalamaVersion>2024.2.32</MetalamaVersion>
        <MetalamaFrameworkRunTimeVersion>2024.2.11</MetalamaFrameworkRunTimeVersion>
    </PropertyGroup>

</Project>