<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.5-preview</MetalamaCompilerVersion>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.6-preview</MetalamaVersion>
    <MetalamaCommunityReleaseVersion>2026.1.6-preview</MetalamaCommunityReleaseVersion>
    <MetalamaCommunityReleaseMainVersion>2026.1.6</MetalamaCommunityReleaseMainVersion>
  </PropertyGroup>
</Project>