<Project>
  <PropertyGroup>
    <MetalamaCompilerVersion Condition="'$(MetalamaCompilerVersion)' == ''">2026.1.15</MetalamaCompilerVersion>
    <MetalamaVersion Condition="'$(MetalamaVersion)' == ''">2026.1.23</MetalamaVersion>
    <MetalamaCommunityReleaseVersion>2026.1.23</MetalamaCommunityReleaseVersion>
    <MetalamaCommunityReleaseMainVersion>2026.1.23</MetalamaCommunityReleaseMainVersion>
  </PropertyGroup>
</Project>